DROP TABLE IF EXISTS notes;

CREATE TABLE notes(
    note_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    content TEXT,
    folder_id INTEGER REFERENCES folders(folder_id)
);